---
title: "dplyr joins"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{assist-dplyr-join}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

* [Back to overview](assist.html)
* [Back to dplyr](dplyr.html)

# Joins

dplyr implements the four most useful joins from SQL

Many to one on

* nothing specified: common variables
* `by = "varname"`: common named variable
* `c("origin" = "faa")`: different variables

left_join(x, y) includes all observations in x, regardless of whether they match or not. This is the most commonly used join because it ensures that you don’t lose observations from your primary table. 

If a match is not unique, a join will add all possible combinations.

* left_join(x, y): all x + matching y
* right_join(x, y): equivalent to left_join(y, x)
* inner_join(x, y): keep only matching x + y
* full_join() includes all observations from x and y.

## Filtering joins

* semi_join(x, y): all x with match in y
* anti_join(x, y): all x without match in y

## Set operations

* intersect(x, y): all rows in both x and y
* union(x, y): rows in either x or y
* setdiff(x, y): rows in x, but not y

